modLoader="javafml"
loaderVersion="[34,)"
license="MIT"
[[mods]]
modId="simplelogin"
version="${version}"
displayName="Simple Login"
authors="Seraph_JACK, Yesterday17"
description="Auth mod based on forge."
