modLoader="javafml"
loaderVersion="[34,)"
license="MIT"
[[mods]]
modId="nedologin"
version="${version}"
displayName="NedoLogin"
authors="marduk.ru"
credits="SimpleLogin authors (Seraph_JACK, Yesterday17)"
description="Auth mod based on forge."
